### ISSUE TITLE
Parameterized tests of Unity Test Runner causes an error

### ISSUE THREAD

**Issue by wingSkyG** [spoiledcat/git-for-unity#29]
### Parameterized tests of Unity Test Runner causes an error
I want to pass  some parameter of object to the test method,then check if object's property is correct.But the test didn't passed,Parameterized tests seems didn't work.
My code is:
`
        [UnityTest]
        public IEnumerator _07_test([ValueSource(nameof(BlockCases))] BlockCase blockCase)
        {
            yield return null;
            
            Assert.AreEqual(blockCase.leftEdgeX, blockCase.block.GetComponent<Block>().GetLeftEdgeX());
        }

        private static IEnumerable BlockCases()
        {
            yield return new BlockCase
            {
                block = BlockFactory.CreateStaticSpecialBlock(TestConst.Position_Center_In_the_GameArea,
                    Consts.BlockType.LBlock1.ToString()),
                leftEdgeX = 4f
            };
        }
        public struct BlockCase
        {
            public GameObject block;
            public float leftEdgeX;
        }

`
And the error is：
`UnityEngine.MissingReferenceException : The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.`
But I did bind a block script to the LBlock1 in the scene.This result let me confused.Am I use ValueSource in a wrong way?

**Comment by CapnRat** [comment]
Hi, this repo doesn't have anything to do with the Unity Test Runner you're speaking about. While this repo uses the unity test framework, it does not maintain it. It's not immediately clear what test framework you're using, but if it's unity's official "com.unity.test-framework" package, then you'll need to take this feedback/question directly to Unity (this repo is a community maintained project, so no one from Unity is monitoring this repo). I recommend reaching out on Unity's forum: https://forum.unity.com/
