### ISSUE TITLE
Error When installing: Tarball downlaod failed

### ISSUE THREAD

**Issue by hashblen** [spoiledcat/git-for-unity#4]
When I try to install the poackage, I get this error:
`Package Manager Window] Cannot perform upm operation: Unable to add package [com.spoiledcat.git@1.0.12]:
  Tarball download failed after [3] attempts. Downloaded [130827] bytes, expected [1049387]:
    shasum check failed for C:\Users\Kynatosh\AppData\Local\Unity\cache\npm\registry.spoiledcat.com\.tmp4648l5NEssCAV3XW\tarball\package.tgz
    Expected: e6fb69a66cdde36a9618e8bbf08658ddf6adccf8
    Actual:   33a60e7b83b7fb4d30b44e0dbd2c2321d2c445cc [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()`

**Comment by shana** [comment]
Ooops, sorry about that, the registry had a little hiccup. Should be fixed now, try again!
