### ISSUE TITLE
wont let me push anything

### ISSUE THREAD

**Issue by amigax** [spoiledcat/git-for-unity#5]
looks promising but I click commit to master and push and my files dont go up.

**Comment by CapnRat** [comment]
Hey, would need some more information. Some things to check:

Do you see any error/warnings in the unity console?

Do you see any errors in the Unity editor log (see where to find the logs [here](https://docs.unity3d.com/Manual/LogFiles.html) )?

Are you able to push from the command line?

Screenshots or video of the issue would be also useful.
